import '../models/app_user.dart';
import '../models/club.dart';
import '../models/event.dart';
import '../models/message.dart';
import '../models/opportunity.dart';

class MockData {
  MockData._();

  static final AppUser studentUser = AppUser(
    id: 'user_001',
    name: 'Amara Diallo',
    email: 'student@alu.edu',
    role: 'student',
    avatar: '👩🏾',
    major: 'Computer Science',
    cohort: 'Class of 2026',
    interests: ['Technology', 'Entrepreneurship', 'Environment'],
    joinedClubIds: ['club_001', 'club_002'],
    rsvpdEventIds: ['event_001'],
    points: 450,
    badges: ['early_bird', 'community_builder'],
  );

  static final AppUser leaderUser = AppUser(
    id: 'user_002',
    name: 'Kwame Asante',
    email: 'leader@alu.edu',
    role: 'club_leader',
    avatar: '👨🏿',
    major: 'Entrepreneurship & Innovation',
    cohort: 'Class of 2025',
    interests: ['Business', 'Technology', 'Leadership'],
    joinedClubIds: ['club_001'],
    rsvpdEventIds: [],
    points: 1250,
    badges: ['leader', 'pioneer', 'community_builder', 'innovator'],
  );

  static const List<Map<String, String>> otherUsers = [
    {'id': 'user_003', 'name': 'Ngozi Okonkwo', 'avatar': '👩🏿', 'major': 'Global Challenges', 'cohort': 'Class of 2026'},
    {'id': 'user_004', 'name': 'Darius Kamau', 'avatar': '👨🏾', 'major': 'Computer Science', 'cohort': 'Class of 2026'},
    {'id': 'user_005', 'name': 'Fatima Al-Hassan', 'avatar': '👩🏽', 'major': 'Business Management', 'cohort': 'Class of 2025'},
    {'id': 'user_006', 'name': 'Tendai Moyo', 'avatar': '👨🏿', 'major': 'Social Sciences', 'cohort': 'Class of 2027'},
    {'id': 'user_007', 'name': 'Asha Kipchoge', 'avatar': '👩🏾', 'major': 'Health Sciences', 'cohort': 'Class of 2026'},
    {'id': 'user_008', 'name': 'Zara Mensah', 'avatar': '👩🏿', 'major': 'Entrepreneurship', 'cohort': 'Class of 2025'},
    {'id': 'user_009', 'name': 'Kofi Acheampong', 'avatar': '👨🏾', 'major': 'Computer Science', 'cohort': 'Class of 2027'},
    {'id': 'user_010', 'name': 'Aisha Ndiaye', 'avatar': '👩🏽', 'major': 'Arts & Media', 'cohort': 'Class of 2026'},
    {'id': 'user_011', 'name': 'Sipho Dlamini', 'avatar': '👨🏿', 'major': 'Education', 'cohort': 'Class of 2027'},
    {'id': 'user_012', 'name': 'Precious Osei', 'avatar': '👩🏾', 'major': 'Global Challenges', 'cohort': 'Class of 2025'},
  ];

  static List<Club> getClubs() => [
    Club(
      id: 'club_001',
      name: 'ALU Tech Hub',
      description:
          'A community for tech enthusiasts, developers, and innovators at ALU. We host hackathons, coding workshops, and connect students with tech opportunities across Africa and beyond.',
      category: 'Technology',
      leaderId: 'user_002',
      leaderName: 'Kwame Asante',
      memberIds: ['user_002', 'user_001', 'user_003', 'user_004', 'user_009'],
      pendingMemberIds: ['user_006', 'user_007'],
      emoji: '💻',
      colorHex: '#1565C0',
      createdAt: DateTime(2025, 9, 1),
      tags: ['Coding', 'AI/ML', 'Hackathon', 'Web Dev'],
      meetingSchedule: 'Every Thursday, 5:00 PM – 7:00 PM',
    ),
    Club(
      id: 'club_002',
      name: "Entrepreneurs' Society",
      description:
          'Empowering student entrepreneurs to build ventures that solve African challenges. From ideation workshops to investor pitch nights, we support your entire journey.',
      category: 'Business',
      leaderId: 'user_008',
      leaderName: 'Zara Mensah',
      memberIds: ['user_008', 'user_001', 'user_005', 'user_010'],
      pendingMemberIds: ['user_011'],
      emoji: '🚀',
      colorHex: '#FF6D00',
      createdAt: DateTime(2025, 9, 5),
      tags: ['Startup', 'Innovation', 'Pitch', 'Funding'],
      meetingSchedule: 'Every Tuesday, 4:00 PM – 6:00 PM',
    ),
    Club(
      id: 'club_003',
      name: 'Environmental Action',
      description:
          'Taking action on climate and environmental challenges facing Africa. We run sustainability projects, tree planting drives, and advocate for eco-friendly campus practices.',
      category: 'Environment',
      leaderId: 'user_003',
      leaderName: 'Ngozi Okonkwo',
      memberIds: ['user_003', 'user_007', 'user_012'],
      pendingMemberIds: [],
      emoji: '🌱',
      colorHex: '#2E7D32',
      createdAt: DateTime(2025, 9, 10),
      tags: ['Sustainability', 'Climate', 'Conservation'],
      meetingSchedule: 'Every Wednesday, 3:30 PM',
    ),
    Club(
      id: 'club_004',
      name: 'Creative Arts Collective',
      description:
          'Celebrating African creativity and artistic expression. Visual art, performance, music, film, and digital media — your canvas is limitless at ALU.',
      category: 'Arts',
      leaderId: 'user_010',
      leaderName: 'Aisha Ndiaye',
      memberIds: ['user_010', 'user_006', 'user_012'],
      pendingMemberIds: [],
      emoji: '🎨',
      colorHex: '#6A1B9A',
      createdAt: DateTime(2025, 9, 12),
      tags: ['Visual Art', 'Music', 'Film', 'Performance'],
      meetingSchedule: 'Every Friday, 4:00 PM',
    ),
    Club(
      id: 'club_005',
      name: 'ALU Debate League',
      description:
          'Sharpening critical thinking and public speaking through competitive debate. We compete in African and global circuits and welcome all levels.',
      category: 'Academic',
      leaderId: 'user_005',
      leaderName: 'Fatima Al-Hassan',
      memberIds: ['user_005', 'user_004', 'user_009'],
      pendingMemberIds: [],
      emoji: '🎤',
      colorHex: '#B71C1C',
      createdAt: DateTime(2025, 9, 15),
      tags: ['Public Speaking', 'Critical Thinking', 'Competition'],
      meetingSchedule: 'Mon & Wed, 5:00 PM',
    ),
    Club(
      id: 'club_006',
      name: 'Sports & Wellness',
      description:
          'Promoting physical health, teamwork, and wellness at ALU. Football, basketball, running clubs, yoga — your mind and body matter.',
      category: 'Sports',
      leaderId: 'user_004',
      leaderName: 'Darius Kamau',
      memberIds: ['user_004', 'user_009', 'user_011'],
      pendingMemberIds: [],
      emoji: '⚽',
      colorHex: '#00838F',
      createdAt: DateTime(2025, 10, 1),
      tags: ['Football', 'Basketball', 'Running', 'Yoga'],
      meetingSchedule: 'Sat & Sun, 7:00 AM',
    ),
    Club(
      id: 'club_007',
      name: 'Mental Health Circle',
      description:
          'A safe, supportive space for ALU students. We run mindfulness sessions, peer counseling, and mental health awareness campaigns.',
      category: 'Wellness',
      leaderId: 'user_007',
      leaderName: 'Asha Kipchoge',
      memberIds: ['user_007', 'user_012', 'user_006'],
      pendingMemberIds: [],
      emoji: '💚',
      colorHex: '#558B2F',
      createdAt: DateTime(2025, 10, 5),
      tags: ['Mindfulness', 'Peer Support', 'Wellness'],
      meetingSchedule: 'Every Sunday, 4:00 PM',
    ),
    Club(
      id: 'club_008',
      name: 'African Culture Club',
      description:
          'Celebrating the rich diversity of African cultures, languages, and traditions at ALU through cultural nights, food festivals, and language exchange.',
      category: 'Culture',
      leaderId: 'user_012',
      leaderName: 'Precious Osei',
      memberIds: ['user_012', 'user_006', 'user_010', 'user_007'],
      pendingMemberIds: [],
      emoji: '🌍',
      colorHex: '#E65100',
      createdAt: DateTime(2025, 10, 8),
      tags: ['Culture', 'Languages', 'Heritage', 'Diversity'],
      meetingSchedule: 'Every Saturday, 2:00 PM',
    ),
  ];

  static List<Event> getEvents() => [
    Event(
      id: 'event_001',
      clubId: 'club_001',
      clubName: 'ALU Tech Hub',
      title: 'ALU Hackathon 2026: Build for Africa',
      description:
          'Our flagship 24-hour hackathon where teams compete to solve pressing African challenges using technology. Prizes worth \$5,000 up for grabs! All skill levels welcome. Teams of 2–4 students.',
      category: 'Competition',
      date: DateTime(2026, 6, 20),
      time: '8:00 AM – 8:00 AM (+1 day)',
      location: 'Innovation Lab, Block C',
      format: 'In-Person',
      maxAttendees: 120,
      rsvpdUserIds: ['user_001', 'user_003', 'user_004', 'user_009'],
      organizerId: 'user_002',
      organizerName: 'Kwame Asante',
      emoji: '🏆',
      colorHex: '#1565C0',
    ),
    Event(
      id: 'event_002',
      clubId: 'club_002',
      clubName: "Entrepreneurs' Society",
      title: 'Startup Pitch Night: Season 3',
      description:
          'Present your startup idea to a panel of ALU alumni investors and mentors. Top 3 teams win mentorship packages and seed funding support. 3-minute pitches, 2-minute Q&A.',
      category: 'Networking',
      date: DateTime(2026, 6, 18),
      time: '5:00 PM – 8:00 PM',
      location: 'Main Auditorium',
      format: 'In-Person',
      maxAttendees: 80,
      rsvpdUserIds: ['user_001', 'user_005', 'user_008'],
      organizerId: 'user_008',
      organizerName: 'Zara Mensah',
      emoji: '🎯',
      colorHex: '#FF6D00',
    ),
    Event(
      id: 'event_003',
      clubId: 'club_003',
      clubName: 'Environmental Action',
      title: 'Campus Tree Planting Drive',
      description:
          'Help us plant 100 trees around the ALU campus this semester. A morning of planting, environmental education, and community building.',
      category: 'Community Service',
      date: DateTime(2026, 6, 22),
      time: '7:00 AM – 11:00 AM',
      location: 'Campus Gardens',
      format: 'In-Person',
      maxAttendees: 50,
      rsvpdUserIds: ['user_003', 'user_007'],
      organizerId: 'user_003',
      organizerName: 'Ngozi Okonkwo',
      emoji: '🌳',
      colorHex: '#2E7D32',
    ),
    Event(
      id: 'event_004',
      clubId: 'club_004',
      clubName: 'Creative Arts Collective',
      title: 'ALU Got Talent: Annual Showcase',
      description:
          'The biggest arts event of the year! Performances, exhibitions, and live art from ALU\'s most talented students. Free to attend for all students.',
      category: 'Cultural',
      date: DateTime(2026, 6, 28),
      time: '6:00 PM – 10:00 PM',
      location: 'Open-Air Amphitheater',
      format: 'In-Person',
      maxAttendees: 300,
      rsvpdUserIds: ['user_010', 'user_006', 'user_001'],
      organizerId: 'user_010',
      organizerName: 'Aisha Ndiaye',
      emoji: '🎭',
      colorHex: '#6A1B9A',
    ),
    Event(
      id: 'event_005',
      clubId: 'club_001',
      clubName: 'ALU Tech Hub',
      title: 'AI & Machine Learning Workshop',
      description:
          'Hands-on workshop covering the fundamentals of ML with Python. Bring your laptop! We will build a real classification model from scratch using real-world data.',
      category: 'Workshop',
      date: DateTime(2026, 7, 5),
      time: '2:00 PM – 6:00 PM',
      location: 'Computer Lab 2, Block A',
      format: 'Hybrid',
      maxAttendees: 40,
      rsvpdUserIds: ['user_001', 'user_004'],
      organizerId: 'user_002',
      organizerName: 'Kwame Asante',
      emoji: '🤖',
      colorHex: '#1565C0',
    ),
    Event(
      id: 'event_006',
      clubId: 'club_005',
      clubName: 'ALU Debate League',
      title: 'Inter-University Debate Championship',
      description:
          'ALU hosts universities from across East Africa. Topic: "Africa should prioritize digital infrastructure over traditional industry." All students welcome to watch!',
      category: 'Competition',
      date: DateTime(2026, 6, 25),
      time: '9:00 AM – 5:00 PM',
      location: 'Conference Hall',
      format: 'In-Person',
      maxAttendees: 150,
      rsvpdUserIds: ['user_005', 'user_004', 'user_009'],
      organizerId: 'user_005',
      organizerName: 'Fatima Al-Hassan',
      emoji: '🗣️',
      colorHex: '#B71C1C',
    ),
    Event(
      id: 'event_007',
      clubId: 'club_007',
      clubName: 'Mental Health Circle',
      title: 'Mindfulness & Exam Prep Workshop',
      description:
          'De-stress before finals! Learn mindfulness techniques, breathing exercises, and study strategies that work with your brain, not against it. Light refreshments provided.',
      category: 'Wellness',
      date: DateTime(2026, 6, 19),
      time: '3:00 PM – 5:00 PM',
      location: 'Wellness Center',
      format: 'In-Person',
      maxAttendees: 30,
      rsvpdUserIds: ['user_007', 'user_012'],
      organizerId: 'user_007',
      organizerName: 'Asha Kipchoge',
      emoji: '🧘',
      colorHex: '#558B2F',
    ),
    Event(
      id: 'event_008',
      clubId: 'club_008',
      clubName: 'African Culture Club',
      title: 'African Night: Unity in Diversity',
      description:
          'A celebration of Africa\'s 54 nations! Traditional food, dance, music, and fashion from across the continent. Wear your national or cultural attire.',
      category: 'Cultural',
      date: DateTime(2026, 6, 30),
      time: '7:00 PM – 11:00 PM',
      location: 'Main Campus Grounds',
      format: 'In-Person',
      maxAttendees: 500,
      rsvpdUserIds: ['user_012', 'user_006', 'user_010', 'user_001'],
      organizerId: 'user_012',
      organizerName: 'Precious Osei',
      emoji: '🌍',
      colorHex: '#E65100',
    ),
    Event(
      id: 'event_009',
      clubId: 'club_006',
      clubName: 'Sports & Wellness',
      title: 'ALU 5K Run for a Cause',
      description:
          'Run, jog, or walk 5K to raise funds for the ALU scholarship fund. All fitness levels welcome. Registration fees support deserving students.',
      category: 'Sports',
      date: DateTime(2026, 6, 17),
      time: '6:30 AM – 9:00 AM',
      location: 'Campus Track & Surroundings',
      format: 'In-Person',
      maxAttendees: 200,
      rsvpdUserIds: ['user_004', 'user_009', 'user_011'],
      organizerId: 'user_004',
      organizerName: 'Darius Kamau',
      emoji: '🏃',
      colorHex: '#00838F',
    ),
    Event(
      id: 'event_010',
      clubId: 'club_002',
      clubName: "Entrepreneurs' Society",
      title: 'Networking Brunch with ALU Alumni',
      description:
          'Connect with ALU alumni who have built successful ventures across Africa. A relaxed brunch setting to build your professional network and get mentorship.',
      category: 'Networking',
      date: DateTime(2026, 7, 8),
      time: '10:00 AM – 1:00 PM',
      location: 'Campus Restaurant',
      format: 'In-Person',
      maxAttendees: 60,
      rsvpdUserIds: ['user_008', 'user_005'],
      organizerId: 'user_008',
      organizerName: 'Zara Mensah',
      emoji: '🤝',
      colorHex: '#FF6D00',
    ),
  ];

  static List<Message> getMessages(String clubId) {
    final messages = <String, List<Message>>{
      'club_001': [
        Message(
          id: 'm1',
          clubId: 'club_001',
          senderId: 'user_002',
          senderName: 'Kwame Asante',
          senderAvatar: '👨🏿',
          senderRole: 'club_leader',
          content:
              '📢 ALU Hackathon 2026 registration is OPEN! Sign up before June 15th. Teams of 2–4 members. Full details in the Events tab.',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          isAnnouncement: true,
        ),
        Message(
          id: 'm2',
          clubId: 'club_001',
          senderId: 'user_003',
          senderName: 'Ngozi Okonkwo',
          senderAvatar: '👩🏿',
          senderRole: 'student',
          content: 'This is so exciting! Is it open to first-years?',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 23)),
        ),
        Message(
          id: 'm3',
          clubId: 'club_001',
          senderId: 'user_002',
          senderName: 'Kwame Asante',
          senderAvatar: '👨🏿',
          senderRole: 'club_leader',
          content: 'Yes! Open to ALL ALU students regardless of year or major. Just bring your passion and creativity 💡',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 22)),
        ),
        Message(
          id: 'm4',
          clubId: 'club_001',
          senderId: 'user_001',
          senderName: 'Amara Diallo',
          senderAvatar: '👩🏾',
          senderRole: 'student',
          content: 'Already forming a team! Who wants to work on a fintech project? 🙋',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 20)),
        ),
        Message(
          id: 'm5',
          clubId: 'club_001',
          senderId: 'user_004',
          senderName: 'Darius Kamau',
          senderAvatar: '👨🏾',
          senderRole: 'student',
          content: 'I\'m in! I can handle backend/API work.',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 19)),
        ),
        Message(
          id: 'm6',
          clubId: 'club_001',
          senderId: 'user_002',
          senderName: 'Kwame Asante',
          senderAvatar: '👨🏿',
          senderRole: 'club_leader',
          content: 'This Thursday\'s workshop covers APIs and data structures — great hackathon prep! See you there.',
          timestamp: DateTime.now().subtract(const Duration(hours: 5)),
        ),
      ],
      'club_002': [
        Message(
          id: 'm7',
          clubId: 'club_002',
          senderId: 'user_008',
          senderName: 'Zara Mensah',
          senderAvatar: '👩🏿',
          senderRole: 'club_leader',
          content:
              '📢 Pitch Night Season 3 is coming June 18! Start preparing your 3-minute pitch. We have 3 investor mentors confirmed.',
          timestamp: DateTime.now().subtract(const Duration(days: 3)),
          isAnnouncement: true,
        ),
        Message(
          id: 'm8',
          clubId: 'club_002',
          senderId: 'user_001',
          senderName: 'Amara Diallo',
          senderAvatar: '👩🏾',
          senderRole: 'student',
          content: 'I have a SaaS idea for farmers I\'ve been working on — finally time to present it! 🌾',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 20)),
        ),
        Message(
          id: 'm9',
          clubId: 'club_002',
          senderId: 'user_005',
          senderName: 'Fatima Al-Hassan',
          senderAvatar: '👩🏽',
          senderRole: 'student',
          content: 'Can we get the pitch deck template again? 🙏',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 18)),
        ),
        Message(
          id: 'm10',
          clubId: 'club_002',
          senderId: 'user_008',
          senderName: 'Zara Mensah',
          senderAvatar: '👩🏿',
          senderRole: 'club_leader',
          content:
              'Template sent! Covers: Problem, Solution, Market Size, Business Model, and Ask. Good luck everyone! 🚀',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 17)),
        ),
      ],
    };

    return messages[clubId] ??
        [
          Message(
            id: 'mx1',
            clubId: clubId,
            senderId: 'system',
            senderName: 'Club Connect',
            senderAvatar: '🌐',
            senderRole: 'system',
            content:
                'Welcome to the club chat! This is where members connect and stay updated. Say hello! 👋',
            timestamp: DateTime.now().subtract(const Duration(days: 7)),
            isAnnouncement: true,
          ),
        ];
  }

  static List<Opportunity> getOpportunities() => [
    Opportunity(
      id: 'opp_001',
      title: 'Google Africa Scholarship 2026',
      description:
          'Full scholarship for African students in CS/Engineering. Covers tuition, accommodation, and a mentorship program with Google engineers.',
      organization: 'Google Africa',
      type: 'Scholarship',
      deadline: 'July 31, 2026',
      applicationLink: 'https://scholarship.google.com',
      emoji: '🎓',
      colorHex: '#1565C0',
      eligibility: 'ALU students in CS or related fields',
    ),
    Opportunity(
      id: 'opp_002',
      title: 'Microsoft Azure Internship – Africa',
      description:
          '12-week paid internship at Microsoft Africa Development Center in Nairobi. Work on real products used by millions across Africa.',
      organization: 'Microsoft',
      type: 'Internship',
      deadline: 'June 30, 2026',
      applicationLink: 'https://careers.microsoft.com',
      emoji: '💼',
      colorHex: '#0078D4',
      eligibility: 'Final year students, technical background required',
    ),
    Opportunity(
      id: 'opp_003',
      title: 'Tony Elumelu Foundation Grant',
      description:
          'USD 5,000 seed capital + business training for African entrepreneurs. One of Africa\'s largest entrepreneurship initiatives.',
      organization: 'Tony Elumelu Foundation',
      type: 'Grant',
      deadline: 'August 15, 2026',
      applicationLink: 'https://tefconnect.com',
      emoji: '💰',
      colorHex: '#FF6D00',
      eligibility: 'African entrepreneurs with an early-stage idea',
    ),
    Opportunity(
      id: 'opp_004',
      title: 'ALU Innovation Fund – Cycle 4',
      description:
          'Internal ALU competition for student innovations. Top 5 projects receive USD 1,000 each + 3 months of incubation support.',
      organization: 'ALU Innovation Office',
      type: 'Competition',
      deadline: 'July 5, 2026',
      applicationLink: 'https://alu.edu/innovation',
      emoji: '🏆',
      colorHex: '#6A1B9A',
      eligibility: 'Current ALU students at any level',
    ),
    Opportunity(
      id: 'opp_005',
      title: 'MIT Solve Youth Program',
      description:
          'MIT\'s global competition for young innovators solving major world challenges in health, education, financial inclusion, and climate.',
      organization: 'MIT Solve',
      type: 'Competition',
      deadline: 'September 1, 2026',
      applicationLink: 'https://solve.mit.edu',
      emoji: '🌐',
      colorHex: '#B71C1C',
      eligibility: 'Ages 18–24 with an innovative solution',
    ),
    Opportunity(
      id: 'opp_006',
      title: 'UN Youth Delegate Programme',
      description:
          'Represent Rwanda/Africa at the UN General Assembly in New York. Develop policy and advocacy skills while engaging with global leaders.',
      organization: 'United Nations',
      type: 'Fellowship',
      deadline: 'July 20, 2026',
      applicationLink: 'https://un.org/youth',
      emoji: '🌍',
      colorHex: '#00838F',
      eligibility: 'Students demonstrating leadership and global citizenship',
    ),
    Opportunity(
      id: 'opp_007',
      title: 'Mastercard Foundation Fellowship',
      description:
          'Fully-funded fellowship for emerging African leaders. Includes study tours, leadership training, and a network of 1,000+ fellows.',
      organization: 'Mastercard Foundation',
      type: 'Fellowship',
      deadline: 'August 30, 2026',
      applicationLink: 'https://mastercardfdn.org',
      emoji: '🌟',
      colorHex: '#E65100',
      eligibility: 'Demonstrated leadership potential, 3.0+ GPA',
    ),
    Opportunity(
      id: 'opp_008',
      title: 'Africa Tech Summit Ambassador',
      description:
          'Represent ATS at your campus, coordinate events, and get free access to Africa\'s leading tech conference.',
      organization: 'Africa Tech Summit',
      type: 'Ambassador Role',
      applicationLink: 'https://africatechsummit.com',
      emoji: '📣',
      colorHex: '#2E7D32',
      eligibility: 'Passionate students with a strong campus network',
    ),
  ];

  static const Map<String, String> badgeLabels = {
    'early_bird': '🐦 Early Bird',
    'community_builder': '🏗️ Builder',
    'leader': '👑 Leader',
    'pioneer': '🚀 Pioneer',
    'innovator': '💡 Innovator',
    'networker': '🤝 Networker',
    'achiever': '🏆 Achiever',
    'scholar': '📚 Scholar',
  };

  static const Map<String, String> badgeDescriptions = {
    'early_bird': 'First to RSVP for an event',
    'community_builder': 'Joined 3 or more clubs',
    'leader': 'Leads a club at ALU',
    'pioneer': 'Among the first 10 members',
    'innovator': 'Submitted to ALU Innovation Fund',
    'networker': 'Attended 5 or more events',
    'achiever': 'Earned 1,000+ community points',
    'scholar': 'Applied for a scholarship',
  };

  static const List<String> clubCategories = [
    'All', 'Technology', 'Business', 'Environment', 'Arts',
    'Academic', 'Sports', 'Wellness', 'Culture',
  ];

  static const List<String> eventCategories = [
    'All', 'Competition', 'Workshop', 'Networking',
    'Cultural', 'Sports', 'Wellness', 'Community Service',
  ];

  static const List<String> clubEmojis = [
    '💻', '🚀', '🌱', '🎨', '🎤', '⚽', '💚', '🌍',
    '📚', '🎭', '🏆', '🤖', '🎓', '💡', '🌐', '🎵',
    '🔬', '🏛️', '✈️', '🎯',
  ];

  static const List<Map<String, String>> clubColors = [
    {'name': 'Navy Blue', 'hex': '#1565C0'},
    {'name': 'Vibrant Orange', 'hex': '#FF6D00'},
    {'name': 'Forest Green', 'hex': '#2E7D32'},
    {'name': 'Deep Purple', 'hex': '#6A1B9A'},
    {'name': 'Crimson', 'hex': '#B71C1C'},
    {'name': 'Teal', 'hex': '#00838F'},
    {'name': 'Olive Green', 'hex': '#558B2F'},
    {'name': 'Deep Orange', 'hex': '#E65100'},
  ];
}
